### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by tjorim** [jakezp/emoncms#1]
When trying to start a docker-compose with mosquitto and emoncms (mqtt enabled), I can't access emoncms. When removing MQTT_HOST (thus disabling MQTT), the container starts fine.

```
emoncms          | 2019-03-11 13:22:39,440 INFO spawned: 'cron' with pid 113
emoncms          | 2019-03-11 13:22:39,443 INFO spawned: 'mysql' with pid 114
emoncms          | 2019-03-11 13:22:39,445 INFO spawned: 'redis' with pid 115
emoncms          | 2019-03-11 13:22:39,447 INFO spawned: 'mqtt_input' with pid 116
emoncms          | 2019-03-11 13:22:39,449 INFO spawned: 'apache2' with pid 117
emoncms          | 2019-03-11 13:22:40,147 INFO exited: mqtt_input (exit status 255; not expected)

emoncms          | 2019-03-11 13:22:41,149 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:22:41,155 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:22:41,156 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:22:41,170 INFO spawned: 'mqtt_input' with pid 300
emoncms          | 2019-03-11 13:22:41,171 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:22:41,605 INFO exited: mqtt_input (exit status 255; not expected)
emoncms          | 2019-03-11 13:22:43,611 INFO spawned: 'mqtt_input' with pid 302
emoncms          | 2019-03-11 13:22:43,709 INFO exited: mqtt_input (exit status 255; not expected)

emoncms          | 2019-03-11 13:22:46,714 INFO spawned: 'mqtt_input' with pid 304
emoncms          | 2019-03-11 13:22:46,795 INFO exited: mqtt_input (exit status 255; not expected)
emoncms          | 2019-03-11 13:22:47,796 INFO gave up: mqtt_input entered FATAL state, too many start retries too quickly
```

**Comment by tjorim** [comment]
Below a log with MQTT disabled. Same unexpected exits, but now with exit status 0.

```
emoncms          | 2019-03-11 13:26:59,024 INFO spawned: 'cron' with pid 110
emoncms          | 2019-03-11 13:26:59,026 INFO spawned: 'mysql' with pid 111
emoncms          | 2019-03-11 13:26:59,028 INFO spawned: 'redis' with pid 112
emoncms          | 2019-03-11 13:26:59,031 INFO spawned: 'mqtt_input' with pid 113
emoncms          | 2019-03-11 13:26:59,033 INFO spawned: 'apache2' with pid 114
emoncms          | 2019-03-11 13:26:59,630 INFO exited: mqtt_input (exit status 0; not expected)

emoncms          | 2019-03-11 13:27:00,632 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:27:00,632 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:27:00,632 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:27:00,633 INFO spawned: 'mqtt_input' with pid 296
emoncms          | 2019-03-11 13:27:00,634 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
emoncms          | 2019-03-11 13:27:00,855 INFO exited: mqtt_input (exit status 0; not expected)
emoncms          | 2019-03-11 13:27:02,859 INFO spawned: 'mqtt_input' with pid 312
emoncms          | 2019-03-11 13:27:03,168 INFO exited: mqtt_input (exit status 0; not expected)

emoncms          | 2019-03-11 13:27:06,174 INFO spawned: 'mqtt_input' with pid 322
emoncms          | 2019-03-11 13:27:06,504 INFO exited: mqtt_input (exit status 0; not expected)
emoncms          | 2019-03-11 13:27:07,506 INFO gave up: mqtt_input entered FATAL state, too many start retries too quickly
```

**Comment by jakezp** [comment]
I've tested / tried with docker-compose. Please provide config / run command, etc. Did you specify username / password?

Could you check /var/log/mqtt_input.log in the container? Also, check "//3 #### MQTT" section in /var/www/html/settings.php.

I'm suspecting /var/www/emoncms/scripts/phpmqtt_input.php may be complaining about credentials.

**Comment by tjorim** [comment]
Here's my

<details>
<summary>docker-composer.yml</summary>

```yaml
version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto:1.5.8
    container_name: mosquitto
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - esnet
  emoncms:
    image: jakezp/emoncms:latest
    container_name: emoncms
    volumes:
      - emon-phpfiwa:/var/lib/phpfiwa
      - emon-phpfina:/var/lib/phpfina
      - emon-phptimeseries:/var/lib/phptimeseries

      - emon-etc-mysql:/etc/mysql
      - emon-mysql:/var/lib/mysql
      - emon-html:/var/www/html
      - emon-crontabs:/var/spool/cron/crontabs

      #- /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80
    networks:
      - esnet
    depends_on:
      - mosquitto
    env_file:
      - .env

volumes:
  mqtt-data:
    driver: local
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-phptimeseries:
    driver: local
  emon-etc-mysql:
    driver: local
  emon-mysql:
    driver: local
  emon-html:
    driver: local
  emon-crontabs:
    driver: local

networks:
  esnet:
```

</details>

and

<details>
<summary>.env</summary>

```
MYSQL_PASSWORD=password
MQTT_HOST=mosquitto
MQTT_PORT=1883
MQTT_USER=''
MQTT_PASS=''
```

</details>

will check and report back the settings- and log-file later.
